language: ruby
sudo: true
rvm:
  - 2.5.5

notifications:
  slack:
    secure: qyOb0DzCp4Q3ahs5wMa9BQehekFT44/Cw28hXZczRTAu1YcnqQUDoiPfKCxI0jD1yhjk7CaDIW4rg/fjdz5/1fM7HpWu97Vi4rehkU6GUlFj3b5oRlHn+Hy+a/uAyrOyJX0t4Qo3xMsGFEkHzu/XuMwm5BYD+O2lSTvl4jnfTc2SmpcpPz8ZNMOXsGsjxBZvmftD5oYA/2j3lAmFGc3Bo/NisfCXK31FzWe+CO1i+yBuq81VvAiFWaR5H1BCUxSn7tYx4dA1XL8oPi1iMEe2bhaLj3+hFqX9hwRZmSxFv5zUw3QOTiGGegaqT8NI/ZBTFOrAcIwi0C0gSroJp2SPDlUS09bF51+VQbtKd/7HV0UbdBExBns+3AsvcgMSVE56VAPNbrailZMywTiPPNxuGgS9egWPN4qJNlwUO8JfdJqzpzY4xjqqAUFZfFD6Pn2ywQg1fsU2aRj/ygHcYjXLGC88FLn+YQnCrdtXQpfE8LmWzx9NiiL2ZQfH7C6EkuKSrxmAJsr08sM1Van9xcPwgK3ZIrJqwyE+LqPIG911x3ozypNXIzfOnEmG9isAocmmRM7mRBrllusoBYLyIJHGTwyz5lf7e8TaN/fB5uv7ZxIhHZGdj8ZayvueZ7H9mzxKA4KN+483UZrVosZw9enVW5VYFW6BGUq/geNXJ3UphN8=

before_install:
  - gem update --system
  - npm install

script:
  - rake lint
